// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCX_PPGxC3De1NrTtUlHKuW3q8532AKTBw',
    appId: '1:468489983561:web:06e04afec71a059e7e9198',
    messagingSenderId: '468489983561',
    projectId: 'posts-app-17923',
    authDomain: 'posts-app-17923.firebaseapp.com',
    storageBucket: 'posts-app-17923.firebasestorage.app',
    measurementId: 'G-64MQX23X0F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAF9RHDIQKhCPTt_P8EWxlqN3mQH6ik3tQ',
    appId: '1:468489983561:android:a148a1bff56778c37e9198',
    messagingSenderId: '468489983561',
    projectId: 'posts-app-17923',
    storageBucket: 'posts-app-17923.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYZzez4C-ihr1dU2kpnZsGkH8ltPQ49Eg',
    appId: '1:468489983561:ios:2be45e85d3cc13867e9198',
    messagingSenderId: '468489983561',
    projectId: 'posts-app-17923',
    storageBucket: 'posts-app-17923.firebasestorage.app',
    iosBundleId: 'com.example.postsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYZzez4C-ihr1dU2kpnZsGkH8ltPQ49Eg',
    appId: '1:468489983561:ios:2be45e85d3cc13867e9198',
    messagingSenderId: '468489983561',
    projectId: 'posts-app-17923',
    storageBucket: 'posts-app-17923.firebasestorage.app',
    iosBundleId: 'com.example.postsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCX_PPGxC3De1NrTtUlHKuW3q8532AKTBw',
    appId: '1:468489983561:web:58f5eff31de0d8277e9198',
    messagingSenderId: '468489983561',
    projectId: 'posts-app-17923',
    authDomain: 'posts-app-17923.firebaseapp.com',
    storageBucket: 'posts-app-17923.firebasestorage.app',
    measurementId: 'G-VBJG53YPFE',
  );
}
